package com.example.monefy.presentation.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class Dimensions(
    val verySmall: Dp,
    val small: Dp,
    val medium: Dp,
    val veryMedium: Dp,
    val big: Dp,
    val iconSize: Dp,
    val bottomBarPieChartIconSize: Dp,
    val heightCategory: Dp,
    val heigthFewCategory: Dp,
    val categoryCardBorderShape: Dp,
    val borderWidth: Dp,
    val categoryCardSize: Dp,
    val fullWeight: Float,
    val colorPickerColumnPadding: Dp,
    val colorPickerWidth: Dp,
    val colorPickerHeight: Dp,
    val pickerPadding: Dp,
    val pickerHeight: Dp,
    val hsvPickerHeight: Dp,
    val mediumSize: Dp,
    val categoryCardElevation: Dp,
    val smallCornerShape: Dp,
    val legendHeight: Dp,
    val diagramBlockHeight: Dp,
    val diagramBlockWidth: Dp,
    val legendCardCornerShape: Dp,
    val canvasLegendWidth: Dp,
    val canvasLegendHeight: Dp,
    val financeCardCornerShape: Dp,
    val historyBlockMaxWidth: Dp,
    val financeMaxWidth: Dp,
    val pieChartRadius: Dp,
    val financeTableHeight: Dp,
    val circleColorSize: Dp,
    val dateRangeSelectorHeight: Dp,
)

val defaultDimensions = Dimensions(
    verySmall = 4.dp,
    small = 8.dp,
    medium = 16.dp,
    big = 32.dp,
    iconSize = 25.dp,
    bottomBarPieChartIconSize = 40.dp,
    heightCategory = 200.dp,
    heigthFewCategory = 100.dp,
    categoryCardBorderShape = 10.dp,
    categoryCardSize = 150.dp,
    borderWidth = 1.dp,
    fullWeight = 1f,
    colorPickerColumnPadding = 30.dp,
    colorPickerWidth = 300.dp,
    colorPickerHeight = 450.dp,
    pickerPadding = 10.dp,
    pickerHeight = 35.dp,
    hsvPickerHeight = 300.dp,
    mediumSize = 70.dp,
    categoryCardElevation = 10.dp,
    smallCornerShape = 2.dp,
    legendHeight = 50.dp,
    diagramBlockHeight = 300.dp,
    diagramBlockWidth = 90.dp,
    legendCardCornerShape = 20.dp,
    canvasLegendWidth = 320.dp,
    canvasLegendHeight = 300.dp,
    financeCardCornerShape = 20.dp,
    financeMaxWidth = 200.dp,
    veryMedium = 24.dp,
    historyBlockMaxWidth = 220.dp,
    pieChartRadius = 120.dp,
    financeTableHeight = 200.dp,
    circleColorSize = 10.dp,
    dateRangeSelectorHeight = 30.dp,
)