package com.example.monefy.presentation.model

/**
 * Перечисление доступных строковых ресурсов для UI.
 */
enum class StringResName {
    ERROR_NO_NAME_AND_COLOR_CATEGORY,
    ERROR_NO_NAME_CATEGORY,
    ERROR_NO_COLOR_CATEGORY,
    ERROR_TO_CREATE_CATEGORY,
    ERROR_NO_NAME_FINANCE_AND_NO_SELECTED_CATEGORY,
    ERROR_NO_NAME_FINANCE,
    ERROR_TO_CREATE_FINANCE,
    ERROR_TO_EDIT_CATEGORY,
    ERROR_TO_EDIT_FINANCE,

    SUCCESS_CATEGORY_CREATED,
    SUCCESS_DELETE_CATEGORY,
    SUCCESS_DELETE_FINANCE,
    SUCCESS_EDIT_CATEGORY,
    SUCCESS_EDIT_FINANCE,
    SUCCESS_FINANCE_CREATED;
}